#pragma once
#include <filesystem>
#include <array>
#include <QDate>
#include <QImage>
#include <QStringList>
#include <QString>
class QApplication;
class QWidget;
struct QtDisplaySettings {
    int scalePercent = 100;
    int windowOpacityPercent = 100;
    int spacingPercent = 100;
    int cornerRadius = 4;
    double windowRounding = 4.0;
    double frameRounding = 4.0;
    double scrollbarRounding = 6.0;
    double grabRounding = 4.0;
    double windowPaddingX = 16.0;
    double windowPaddingY = 8.0;
    double framePaddingX = 8.0;
    double framePaddingY = 0.0;
    double itemSpacingX = 8.0;
    double itemSpacingY = 6.0;
    std::array<QString, 18> windowBackgrounds{};
    double backgroundAlpha = 0.25;
    bool backgroundTiled = false;
    double backgroundTileScale = 1.0;
    bool compactRows = false;
    bool fullscreen = false;
    bool decorated = true;
    bool minimizeToTray = false;
    bool deadlineNotificationsWhenClosed = false;
    QString lastProfileId;
    int lastPage = 0;
    int profileViewMode = 1;
    int profileSkillSort = 0;
    int profileSkillWeightCategory = 0;
    double profileSkillWeightMin = 0.0;
    double profileSkillWeightMax = 2.0;
    int taskStatusFilter = 0;
    int taskPriorityFilter = 0;
    int taskQuickFilter = 0;
    int taskCreatedRange = 0;
    int taskSortMode = 0;
    QString taskAssigneeProfileId;
    QString taskProjectId;
    QString taskPipelineStepId;
    QString catalogProfessionId;
    int catalogSortMode = 0;
    int catalogGroupMode = 0;
    int catalogWeightCategory = 0;
    int reportView = 0;
    int reportDateRange = 0;
    bool reportComparePrevious = false;
    QDate reportDateFrom;
    QDate reportDateTo;
    QString projectFilter;
    int projectSortMode = 0;
    bool projectsOverdueOnly = false;
    bool projectsXpPendingOnly = false;
    int auditSourceFilter = 0;
    bool logShowInfo = true;
    bool logShowWarning = true;
    bool logShowError = true;
    QString logSourceFilter;
    QString logFilter;
    bool logAutoScroll = true;
    bool logCompactView = false;
    QString adminStatsSearch;
    bool adminStatsIncludeArchived = true;
    int adminStatsRankFilter = 0;
    int adminStatsView = 0;
    bool adminStatsAutoRefresh = true;
    int adminStatsRefreshSeconds = 30;
    int adminStatsInactivityDays = 30;
};
struct QtLayoutPreset {
    QString name;
    int scalePercent = 100;
    int windowOpacityPercent = 100;
    int spacingPercent = 100;
    int cornerRadius = 4;
    double windowRounding = 4.0;
    double frameRounding = 4.0;
    double scrollbarRounding = 6.0;
    double grabRounding = 4.0;
    double windowPaddingX = 16.0;
    double windowPaddingY = 8.0;
    double framePaddingX = 8.0;
    double framePaddingY = 0.0;
    double itemSpacingX = 8.0;
    double itemSpacingY = 6.0;
    bool compactRows = false;
    bool fullscreen = false;
    bool decorated = true;
    std::array<QString, 18> windowBackgrounds{};
    double backgroundAlpha = 0.25;
    bool backgroundTiled = false;
    double backgroundTileScale = 1.0;
};
QStringList QtBackgroundPageNames();
QStringList ListQtBackgroundImages(const std::filesystem::path& directory);
QImage LoadQtBackgroundImage(const std::filesystem::path& directory, const QString& relativePath);
bool ShowQtBackgroundSettings(QWidget* parent, const std::filesystem::path& directory, QtDisplaySettings& settings);
QtDisplaySettings LoadQtDisplaySettings(const std::filesystem::path& directory);
bool SaveQtDisplaySettings(const std::filesystem::path& directory, const QtDisplaySettings& settings);
QStringList ListQtLayoutPresets(const std::filesystem::path& directory);
bool LoadQtLayoutPreset(const std::filesystem::path& directory, const QString& name, QtLayoutPreset* preset);
bool ResetQtUiSettings(const std::filesystem::path& directory);
bool SaveQtLayoutPreset(const std::filesystem::path& directory, const QtLayoutPreset& preset, QString* error = nullptr);
bool DeleteQtLayoutPreset(const std::filesystem::path& directory, const QString& name, QString* error = nullptr);
bool IsQtLayoutPresetDeletable(const std::filesystem::path& directory, const QString& name);
bool ApplyQtBuiltInLayoutPreset(const QString& name, QtLayoutPreset* preset);
void ApplyQtDisplaySettings(QApplication& app, const QtDisplaySettings& settings);
bool ShowQtDisplaySettings(QWidget* parent, const std::filesystem::path& directory, QtDisplaySettings& settings);
