#pragma once
#include "QtWorkspace.h"
#include "QtProfileSession.h"
#include "QtDisplaySettings.h"
#include "QtModelViewer.h"
#include "AppDomainTypes.h"
#include <QMainWindow>
#include <array>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>

struct QtAdminProfileStatsRow {
    std::string id;
    std::string name;
    int level = 0;
    int totalXp = 0;
    std::int64_t lastTaskTimestamp = 0;
    int recoveryTasksRemaining = 0;
    int achievementsTotal = 0;
    int achievementsActive = 0;
    std::array<int, 5> categoryScores{};
    bool archived = false;
};

class QComboBox;
class QDateEdit;
class QWidget;
class QLabel;
class QLineEdit;
class QListWidget;
class QPushButton;
class QTableWidget;
class QTextBrowser;
class QAction;
class QSlider;
class QCheckBox;
class QToolButton;
class QProgressBar;
class QMenu;
class QAction;
class QSpinBox;
class QDoubleSpinBox;
class QLabel;
class QtReportChart;
class QtLogActivityChart;
class QtProfileAnalytics;
class QSystemTrayIcon;
class QCloseEvent;
class QHideEvent;
class QEvent;
class QTimer;
class QPropertyAnimation;
class QtBackgroundSurface;
class QScrollArea;

class QtWindow : public QMainWindow {
public:
    explicit QtWindow(QtWorkspace& workspace);
    void recordRuntimeMessage(AppLogLevel level, const QString& text);
private:
    void closeEvent(QCloseEvent* event) override;
    void hideEvent(QHideEvent* event) override;
    void changeEvent(QEvent* event) override;
    bool eventFilter(QObject* watched, QEvent* event) override;
    bool reload();
    void render();
    void details();
    void authenticate();
    void changeAdminPassword();
    void authenticateProfile();
    void showShortcutHelp();
    void createEntry(bool edit = false);
    void deleteEntry();
    void movePipeline(int delta);
    void changeStatus();
    void bulkEditTasks();
    void exportReport();
    void exportTasks(bool textFormat);
    void exportAudit();
    void exportLogs();
    void exportAdminProfileStats();
    void refreshAdminProfileStats();
    void reapplyRules();
    void grantDirectXp();
    void applyProfileRank();
    void adjustWallet();
    void showWalletHistory();
    void showProfileHistory();
    void exportProfileReport(bool csv);
    void exportStorageHealthReport();
    void cleanupStrayStorage();
    void checkDeadlineReminders();
    void checkMissedDeadlineReminders();
    void updateBanner();
    void pullCloud();
    void runQuickCloudSync();
    void updateCloudQuickStatus();
    void runAutomaticCloudSync();
    void downloadCloudRelease();
    void launchCloudRelease();
    void previewCloudPush();
    void resolveCloudConflict();
    void resolveStorageConflict();
    void loadSelectedModel();
    void saveModelSettings();
    void updateModelSettingsFromControls();
    void saveDisplayContext();
    void updateNavigationIndicator(bool animate);
    void updateResponsiveShell();
    void updateResponsiveHeader();
    void updateProjectColumnLayout();
    void updatePipelineColumnLayout();
    void updateProfileTaskColumnLayout();
    void refreshTaskFilterChoices();
    void refreshCatalogProfessionChoices();
    bool requireAdmin();
    void message(const std::string& error);
    void appendLog(AppLogLevel level, const std::string& source, const std::string& message);
    void loadAppLogs();
    bool saveAppLogs();
    QString selectedId() const;
    void openProfileTasksFilter(int index);
    void openProjectTasksFilter(const QString& projectId, int quickFilter);
    void showProfessionBindings();
    void rememberRecentProfile(const QString& profileId);
    void updateRecentProfileMenu();
    QtWorkspace& workspace_;
    bool admin_ = false;
    QtProfileSession profileSession_;
    QtDisplaySettings displaySettings_;
    QtBackgroundSurface* backgroundSurface_ = nullptr;
    QAction* profileAccessAction_;
    QAction* adminLoginAction_ = nullptr;
    QAction* adminPasswordAction_;
    QAction* legacyDataPathCopy_ = nullptr;
    QAction* ownPasswordAction_;
    QAction* windowFullscreenAction_ = nullptr;
    QAction* windowDecoratedAction_ = nullptr;
    QAction* storageHealthReportAction_;
    QAction* storageCleanupAction_;
    QComboBox* profiles_;
    QWidget* headerContent_ = nullptr;
    QScrollArea* headerScroll_ = nullptr;
    QLabel* headerProfileLabel_ = nullptr;
    QPushButton* headerRefresh_ = nullptr;
    QToolButton* headerOverflowButton_ = nullptr;
    QMenu* headerOverflowMenu_ = nullptr;
    std::array<QAction*, 6> headerFoldedActions_{};
    QAction* headerFoldedSeparator_ = nullptr;
    bool headerLayoutUpdating_ = false;
    QListWidget* navigation_;
    QWidget* navigationIndicator_ = nullptr;
    QPropertyAnimation* navigationIndicatorAnimation_ = nullptr;
    QLineEdit* search_;
    QComboBox* statusFilter_;
    QComboBox* priorityFilter_;
    QComboBox* quickTaskFilter_;
    QComboBox* taskCreatedRange_;
    QComboBox* taskSort_;
    QComboBox* taskAssigneeFilter_;
    QPushButton* taskFilterReset_;
    QComboBox* taskProjectFilter_;
    QComboBox* taskPipelineFilter_;
    QComboBox* catalogProfessionFilter_;
    QComboBox* catalogSort_;
    QComboBox* catalogGroup_;
    QComboBox* catalogWeightCategory_;
    QPushButton* catalogFilterReset_;
    QComboBox* reportView_;
    QComboBox* reportDateRange_;
    QCheckBox* reportCompare_;
    QDateEdit* reportFrom_;
    QDateEdit* reportTo_;
    QWidget* reportCustomRange_;
    QComboBox* projectSort_;
    QPushButton* projectFilterReset_;
    QComboBox* auditSourceFilter_;
    QWidget* auditFilters_;
    QLineEdit* auditActorFilter_;
    QLineEdit* auditObjectFilter_;
    QLineEdit* auditFieldFilter_;
    QPushButton* auditFilterReset_;
    QCheckBox* projectsOverdue_;
    QCheckBox* projectsXpPending_;
    QLabel* summary_;
    QWidget* listEmptyState_ = nullptr;
    QLabel* listEmptyIcon_ = nullptr;
    QLabel* listEmptyTitle_ = nullptr;
    QLabel* listEmptyDescription_ = nullptr;
    QLabel* taskPipelineSummary_;
    QtReportChart* statisticsChart_;
    QtLogActivityChart* logActivityChart_;
    QLabel* title_;
    QLabel* mode_;
    QLabel* banner_;
    QWidget* profileMetrics_;
    QWidget* profileOverview_ = nullptr;
    QToolButton* profileIdentityCopy_ = nullptr;
    QToolButton* profileRecentButton_ = nullptr;
    QMenu* profileRecentMenu_ = nullptr;
    QLabel* profileCollectionSummary_ = nullptr;
    QWidget* profileAchievementPreview_ = nullptr;
    QLabel* profileAchievementIcons_[3]{};
    QLabel* profileAchievementOverflow_ = nullptr;
    QLabel* profileStateValues_[3]{};
    QLabel* profileSignalValues_[4]{};
    QLabel* profileSignalDetails_[4]{};
    QTableWidget* profileBalanceTable_ = nullptr;
    QProgressBar* profileBalanceBars_[3]{};
    QWidget* profileTaskBriefCard_ = nullptr;
    QLabel* profileTaskSummary_ = nullptr;
    QTableWidget* profileTaskBriefTable_ = nullptr;
    QLabel* profileTaskEmpty_ = nullptr;
    QWidget* profileRecentActionsCard_ = nullptr;
    QLabel* profileRecentActionsSummary_ = nullptr;
    QPushButton* profileOverviewTaskButtons_[5]{};
    QPushButton* profileOverviewAnalytics_ = nullptr;
    QPushButton* profileOverviewXp_ = nullptr;
    QWidget* profileRankControls_ = nullptr;
    QComboBox* profileRankChoice_ = nullptr;
    QPushButton* profileRankApply_ = nullptr;
    QWidget* profileViewModes_;
    QPushButton* profileViewModeButtons_[3];
    QWidget* profileTaskActions_;
    QPushButton* profileTaskFilterButtons_[4];
    QWidget* profileSkillFilters_;
    QtProfileAnalytics* profileAnalytics_;
    QComboBox* profileSkillSort_;
    QComboBox* profileSkillWeightCategory_;
    QDoubleSpinBox* profileSkillWeightMin_;
    QDoubleSpinBox* profileSkillWeightMax_;
    QPushButton* profileSkillFilterReset_;
    QWidget* pomodoro_;
    QWidget* bottomActions_;
    QWidget* modelPage_;
    QWidget* modelSettingsPage_;
    QtModelViewer* modelViewer_;
    QtModelSettings modelSettings_;
    QComboBox* modelChoice_;
    QLineEdit* modelFilter_;
    QLineEdit* modelPath_;
    QLabel* modelChoiceCount_;
    QPushButton* modelFilterReset_;
    QPushButton* modelChoiceRefresh_;
    std::vector<QString> modelNames_;
    QSlider* modelYaw_;
    QSlider* modelPitch_;
    QSlider* modelZoom_;
    QSlider* modelSpeed_;
    QCheckBox* modelAutoRotate_;
    QPushButton* modelColor_;
    QLabel* modelStatus_;
    QTimer* modelTimer_;
    bool restoringModelSettings_ = false;
    void rebuildModelChoices();
    void refreshModelChoices();
    QLabel* profileValues_[5];
    std::string pendingProfileTaskId_;
    QTableWidget* table_ = nullptr;
    QTextBrowser* details_;
    QPushButton* primary_;
    QToolButton* dragHandle_;
    QToolButton* shortcutLauncher_ = nullptr;
    QMenu* shortcutMenu_ = nullptr;
    QToolButton* cloudQuickButton_ = nullptr;
    QToolButton* pomodoroQuickButton_ = nullptr;
    QMenu* pomodoroQuickMenu_ = nullptr;
    QPushButton* detailsToggle_;
    QPushButton* changeStatus_;
    QPushButton* manualTaskXp_ = nullptr;
    QPushButton* bulkEdit_;
    QPushButton* bulkDelete_;
    QToolButton* taskSelectionTools_;
    QPushButton* editEntry_;
    QPushButton* professionBindings_ = nullptr;
    QPushButton* deleteEntry_;
    QPushButton* moveUp_;
    QPushButton* moveDown_;
    QPushButton* pipelineMap_;
    QPushButton* pipelineFilterReset_;
    QPushButton* advanceStage_;
    QPushButton* achievements_;
    QPushButton* removeSpirit_;
    QPushButton* exportReport_;
    QToolButton* exportTasks_;
    QPushButton* exportAudit_;
    QPushButton* exportLogs_;
    QPushButton* clearLogs_;
    QCheckBox* logInfo_;
    QCheckBox* logWarnings_;
    QCheckBox* logErrors_;
    QComboBox* logSourceFilter_;
    QPushButton* logPresetAll_;
    QPushButton* logPresetWarningsErrors_;
    QPushButton* logPresetErrors_;
    QCheckBox* logAutoScroll_;
    QCheckBox* logCompactView_;
    QWidget* adminStatsKpiRow_;
    std::array<QLabel*, 4> adminStatsKpiValues_{};
    std::array<QLabel*, 4> adminStatsKpiNotes_{};
    QWidget* adminStatsFilters_;
    QLineEdit* adminStatsSearch_;
    QCheckBox* adminStatsArchived_;
    QComboBox* adminStatsRank_;
    QComboBox* adminStatsView_;
    QCheckBox* adminStatsAutoRefresh_;
    QSpinBox* adminStatsRefreshSeconds_;
    QSpinBox* adminStatsInactivityDays_;
    QLabel* adminStatsInactivityLabel_;
    QWidget* adminStatsInactivityField_;
    QWidget* adminStatsRefreshIntervalField_;
    QPushButton* adminStatsRefreshButton_;
    QPushButton* adminStatsReset_;
    std::int64_t adminStatsLastRefresh_ = 0;
    std::vector<QtAdminProfileStatsRow> adminStatsRows_;
    int adminStatsUnreadableProfiles_ = 0;
    QPushButton* reapplyRules_;
    QPushButton* directXp_;
    QPushButton* walletAdjust_;
    QPushButton* walletHistory_;
    QPushButton* profileHistory_;
    QToolButton* profileExport_;
    QToolButton* projectFocus_;
    QToolButton* projectPortfolioTasks_;
    QPushButton* openShortcut_;
    QPushButton* cloudPull_;
    QPushButton* cloudPushPreview_;
    QPushButton* cloudResolve_;
    QPushButton* storageResolve_;
    QToolButton* cloudReleaseButton_;
    QAction* cloudReleaseDownload_;
    QAction* cloudReleaseLaunch_;
    int bannerIndex_ = 0;
    std::vector<AppLogEntry> appLogs_;
    std::vector<AppLogEntry> appLogPending_;
    bool appLogClearPending_ = false;
    bool appLogPersistenceWarning_ = false;
    std::int64_t lastReminderCheckAt_ = 0;
    std::int64_t lastCloudAutoSyncAt_ = 0;
    std::int64_t lastCloudStatusScanAt_ = 0;
    QTimer* cloudAutoSyncTimer_ = nullptr;
    bool reminderStatePersistenceWarning_ = false;
    QSystemTrayIcon* trayIcon_ = nullptr;
    std::unordered_set<std::string> remindedDeadlineTaskIds_;
};
