#pragma once
#include "QtWorkspace.h"
#include "QtProfileSession.h"
#include "QtDisplaySettings.h"
#include "QtModelViewer.h"
#include "AppDomainTypes.h"
#include <QMainWindow>
#include <unordered_set>

class QComboBox;
class QDateEdit;
class QWidget;
class QLabel;
class QLineEdit;
class QListWidget;
class QPushButton;
class QTableWidget;
class QTextBrowser;
class QAction;
class QSlider;
class QCheckBox;
class QToolButton;
class QtReportChart;
class QSystemTrayIcon;
class QCloseEvent;

class QtWindow : public QMainWindow {
public:
    explicit QtWindow(QtWorkspace& workspace);
private:
    void closeEvent(QCloseEvent* event) override;
    bool reload();
    void render();
    void details();
    void authenticate();
    void authenticateProfile();
    void showShortcutHelp();
    void createEntry(bool edit = false);
    void deleteEntry();
    void movePipeline(int delta);
    void changeStatus();
    void bulkEditTasks();
    void exportReport();
    void exportAudit();
    void exportLogs();
    void reapplyRules();
    void grantDirectXp();
    void adjustWallet();
    void showWalletHistory();
    void checkDeadlineReminders();
    void updateBanner();
    void pullCloud();
    void resolveCloudConflict();
    void resolveStorageConflict();
    void loadSelectedModel();
    void saveModelSettings();
    void updateModelSettingsFromControls();
    void saveDisplayContext();
    void refreshTaskFilterChoices();
    bool requireAdmin();
    void message(const std::string& error);
    void appendLog(AppLogLevel level, const std::string& source, const std::string& message);
    void loadAppLogs();
    bool saveAppLogs() const;
    QString selectedId() const;
    QtWorkspace& workspace_;
    bool admin_ = false;
    QtProfileSession profileSession_;
    QtDisplaySettings displaySettings_;
    QAction* profileAccessAction_;
    QAction* ownPasswordAction_;
    QComboBox* profiles_;
    QListWidget* navigation_;
    QLineEdit* search_;
    QComboBox* statusFilter_;
    QComboBox* priorityFilter_;
    QComboBox* quickTaskFilter_;
    QComboBox* taskProjectFilter_;
    QComboBox* taskPipelineFilter_;
    QComboBox* reportView_;
    QComboBox* reportDateRange_;
    QDateEdit* reportFrom_;
    QDateEdit* reportTo_;
    QWidget* reportCustomRange_;
    QComboBox* projectSort_;
    QComboBox* auditSourceFilter_;
    QWidget* auditFilters_;
    QLineEdit* auditActorFilter_;
    QLineEdit* auditObjectFilter_;
    QLineEdit* auditFieldFilter_;
    QPushButton* auditFilterReset_;
    QCheckBox* projectsOverdue_;
    QCheckBox* projectsXpPending_;
    QLabel* summary_;
    QtReportChart* statisticsChart_;
    QLabel* title_;
    QLabel* mode_;
    QLabel* banner_;
    QWidget* profileMetrics_;
    QWidget* pomodoro_;
    QWidget* bottomActions_;
    QWidget* modelPage_;
    QWidget* modelSettingsPage_;
    QtModelViewer* modelViewer_;
    QtModelSettings modelSettings_;
    QComboBox* modelChoice_;
    QLineEdit* modelPath_;
    QSlider* modelYaw_;
    QSlider* modelPitch_;
    QSlider* modelZoom_;
    QSlider* modelSpeed_;
    QCheckBox* modelAutoRotate_;
    QPushButton* modelColor_;
    QLabel* modelStatus_;
    QTimer* modelTimer_;
    bool restoringModelSettings_ = false;
    QLabel* profileValues_[5];
    QTableWidget* table_;
    QTextBrowser* details_;
    QPushButton* primary_;
    QToolButton* dragHandle_;
    QPushButton* detailsToggle_;
    QPushButton* changeStatus_;
    QPushButton* bulkEdit_;
    QPushButton* editEntry_;
    QPushButton* deleteEntry_;
    QPushButton* moveUp_;
    QPushButton* moveDown_;
    QPushButton* advanceStage_;
    QPushButton* achievements_;
    QPushButton* removeSpirit_;
    QPushButton* exportReport_;
    QPushButton* exportAudit_;
    QPushButton* exportLogs_;
    QPushButton* clearLogs_;
    QCheckBox* logInfo_;
    QCheckBox* logWarnings_;
    QCheckBox* logErrors_;
    QPushButton* reapplyRules_;
    QPushButton* directXp_;
    QPushButton* walletAdjust_;
    QPushButton* walletHistory_;
    QPushButton* projectFocus_;
    QPushButton* openShortcut_;
    QPushButton* cloudPull_;
    QPushButton* cloudResolve_;
    QPushButton* storageResolve_;
    int bannerIndex_ = 0;
    std::vector<AppLogEntry> appLogs_;
    bool appLogPersistenceWarning_ = false;
    QSystemTrayIcon* trayIcon_ = nullptr;
    std::unordered_set<std::string> remindedDeadlineTaskIds_;
};
